name: pull-request

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install GTest Manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v1
    - name: Configure
      run: cmake -S . -B build -DOPENSSL_ROOT_DIR=/usr/local/ssl
    - name: Make
      run: camke --build build
    - name: Run Test
      run: cd build && ctest