name: Gennerate Library Files

on:
  push:
    branches: [ feature/ios-lib ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
    - run: cd ./cross-platform/android/jni && ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
    - uses: actions/upload-artifact@v2
      with:
        name: android-lib-artifact
        path: cross-platform/android/jni/libs
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./cross-platform/ios/ios-lib && xcodebuild -scheme ios-lib CONFIGURATION_BUILD_DIR=build
      - uses: actions/upload-artifact@v2
        with:
          name: android-lib-artifact
          path: cross-platform/ios/ios-lib/build